{
 "title": "Async Relaxed Consistency",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Processed Gradients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ray_processed_gradients{Experiment=\"relaxed consistency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GCS Storage Operating Count Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ray_gcs_storage_operation_count_total",
     "legendFormat": "__auto"
    },
    { "expr": "ray_object_manager_bytes", "legendFormat": "__auto" },
    { "expr": "ray_object_store_memory", "legendFormat": "__auto" },
    {
     "expr": "ray_spill_manager_objects_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ray_training_accuracy{Experiment=\"relaxed consistency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ray_training_loss{Experiment=\"relaxed consistency\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}