{
 "title": "Ray train loss",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SYNC Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ray_training_accuracy{Experiment=\"sync control\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASYNC Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ray_training_accuracy{Experiment=\"async control\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYNC Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ray_training_loss{Experiment=\"sync control\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHAIN REPLICATION Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ray_training_accuracy{Experiment=\"chain replication\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHAIN REPLICATION Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ray_training_loss{Experiment=\"chain replication\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASYNC Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ray_training_loss{Experiment=\"async control\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}