{
 "title": "Final Experiment Metrics Dashboard (Use for Experiments)",
 "time": { "from": "2024-05-30T06:14:41.765Z", "to": "2024-05-30T06:16:50.185Z" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ray_node_cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Zookeeper Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ray_zookeeper_writes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Zookeeper Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ray_zookeeper_reads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ray Network Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "ray_node_network_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ray Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "ray_node_network_received", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ray Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "ray_object_store_used_memory{job=\"ray\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Nodes Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "ray_node_cpu_count{job=\"ray\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Processed Gradients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "ray_processed_gradients{job=\"ray\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "ray_training_accuracy{job=\"ray\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "ray_training_loss{job=\"ray\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}